{"name": "使用无效凭证登录", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_134.0.6998", "trace": "@pytest.fixture(scope=\"function\")\n    def browser():\n        # 使用WebDriver Manager自动管理浏览器驱动\n        options = webdriver.ChromeOptions()\n        options.add_argument(\"--headless\")  # 无头模式，不显示浏览器\n        options.add_argument(\"--no-sandbox\")\n        options.add_argument(\"--disable-dev-shm-usage\")\n    \n>       driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n\n..\\conftest.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\.venv\\Lib\\site-packages\\webdriver_manager\\chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\n..\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_driver_download_url())\n..\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\chrome.py:40: in get_driver_download_url\n    driver_version_to_download = self.get_driver_version_to_download()\n..\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver.py:51: in get_driver_version_to_download\n    self._driver_to_download_version = self._version if self._version not in (None, \"latest\") else self.get_latest_release_version()\n..\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\chrome.py:62: in get_latest_release_version\n    resp = self._http_client.get(url=latest_release_url)\n..\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py:37: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_134.0.6998\n\n..\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py:16: ValueError"}, "start": 1743466690943, "stop": 1743466690943, "uuid": "bcfc53cc-172c-4541-8424-409c4d04e784", "historyId": "469e1c7a7a786adeb6bc7642147fd103", "testCaseId": "469e1c7a7a786adeb6bc7642147fd103", "fullName": "tests.test_web_ui.TestLogin#test_failed_login", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "失败登录"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_web_ui"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "P14s"}, {"name": "thread", "value": "15112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_web_ui"}]}